GET http://localhost:8080/all

###

GET http://localhost:8080/all/111

###

POST http://localhost:8080/line/111

###

POST http://localhost:8080/line/501

###

DELETE http://localhost:8080/line/501

###

POST http://localhost:8080/line/111/5

###

DELETE http://localhost:8080/line

###
